//
//  CodeGenerationContext.swift
//
//
//  Created by Kamil Strzelecki on 16/09/2023.
//

import Foundation

final class CodeGenerationContext {
    let additionalImports: [String]
    var storybookComponentProvidersAccessPaths = [AccessPath]()

    init(additionalImports: [String]) {
        self.additionalImports = additionalImports
    }

    func finalize() -> String {
        """
        //
        // Generated by StorybookComposer by Kamil Strzelecki.
        //

        \(imports())

        extension StorybookView: SwiftUI.View {
            public var body: some SwiftUI.View {
                StorybookComposer.StorybookComponentList {
                    \(rows(indentationLevel: 3))
                }
            }
        }
        """
    }

    private func imports() -> String {
        (["SwiftUI", "StorybookComposer"] + additionalImports)
            .map { "import \($0)" }
            .joined(indentationLevel: 0)
    }

    private func rows(indentationLevel: Int) -> String {
        storybookComponentProvidersAccessPaths
            .map { "StorybookComponentRow(provider: \($0.description))" }
            .joined(indentationLevel: indentationLevel)
    }
}
